server:
  port: 8084

spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    hikari:
      max-lifetime: 600000
    url: jdbc:postgresql://localhost:5432/the_game_user
    username: postgres
    password: dontgotosql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: auth-service

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B59701231BZCZWQWRXCVXQWEQWREYGCX34234VXCVERW
      expiration: 660000
      #      expiration: 15000
      refresh-token:
        expiration: 604800000 # 7 days
token:
  key:
    value: Udh5YQlFnpMuEwltT7m4q8Dcsvz+G28Iqru3kk3vJx8=
  ivParameter:
    value: anjbBT/W+R6ycBK2Akx1Ug==