server:
  port: 8084

spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    hikari:
      max-lifetime: 600000
    url: jdbc:postgresql://postgres:5432/the_game_user
    username: postgres
    password: dontgotosql

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: auth-service

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B59701231BZCZWQWRXCVXQWEQWREYGCX34234VXCVERW
      expiration: 1900000
      refresh-token:
        expiration: 3600000
      token-encryption:
        key-value: Udh5YQlFnpMuEwltT7m4q8Dcsvz+G28Iqru3kk3vJx8=
        ivParameter: anjbBT/W+R6ycBK2Akx1Ug==
        algorithm: AES
        transformation: AES/CBC/PKCS5Padding
        key-size: 256


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  observations:
    key-values:
      application: auth-service
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
