server:
  port: 8085

spring:
  application:
    name: messaging-service
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      uri: mongodb://mongo:dontgotosql@mongo:27017/user_session
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: messaging-service