server:
  port: 8085

spring:
  main:
    web-application-type: servlet
  application:
    name: messaging-service
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      uri: mongodb://mongo:dontgotosql@localhost:27017/user_session
      auto-index-creation: true
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true


#broker:
#  relay:
#    host: ${BROKER_HOST:localhost}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: messaging-service