server:
  port: 8085

spring:
  main:
    web-application-type: servlet
  application:
    name: websocket-service
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      uri: mongodb://mongo:dontgotosql@localhost:27017/user_session
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: websocket-service

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  observations:
    key-values:
      application: websocket-service
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true