server:
  port: 8083

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: gateway