global:
  scrape_interval: 35s
  scrape_timeout: 35s
  evaluation_interval: 35s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9090

  - job_name: 'eureka-discovery'
    metrics_path: '/actuator/prometheus'
    scheme: http

    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
        refresh_interval: 30s

    relabel_configs:
      - source_labels: [__meta_eureka_app_instance_ip_addr, __meta_eureka_app_instance_port]
        regex: '(.*);(\d+)'
        replacement: '${1}:${2}'
#        replacement: 'host.docker.internal:${2}'
        target_label: __address__

      - source_labels: [__meta_eureka_app_instance_id]
        target_label: instance

      - source_labels: [__meta_eureka_app_instance_secure_vip_address]
        replacement: '${1}'
        target_label: job

      - source_labels: [__meta_eureka_app_instance_secure_vip_address]
        replacement: '${1}'
        target_label: application

#  - job_name: 'api-gateway'
#    scheme: http
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8083']
#        labels:
#          application: 'api-gateway'
#    authorization:
#      type: Bearer
#      credentials: 'Bearer prometheus9090auth'
#
#  - job_name: 'auth-service'
#    scheme: http
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8084']
#        labels:
#          application: 'auth-service'
#    authorization:
#      type: Bearer
#      credentials: 'Bearer prometheus9090auth'
#
#  - job_name: 'websocket-service'
#    scheme: http
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8085']
#        labels:
#          application: 'websocket-service'
#    authorization:
#      type: Bearer
#      credentials: 'Bearer prometheus9090auth'
#
#  - job_name: 'conversation-service'
#    scheme: http
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8087']
#        labels:
#          application: 'conversation-service'
#    authorization:
#      type: Bearer
#      credentials: 'Bearer prometheus9090auth'
#
#  - job_name: 'user-service'
#    scheme: http
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8082']
#        labels:
#          application: 'user-service'
#    authorization:
#      type: Bearer
#      credentials: 'Bearer prometheus9090auth'
#
#  - job_name: 'frontend'
#    scheme: http
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8080']
#        labels:
#          application: 'frontend'
#    authorization:
#      type: Bearer
#      credentials: 'Bearer prometheus9090auth'