server:
  port: 8082

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    hikari:
      max-lifetime: 600000
    url: jdbc:postgresql://postgres:5432/thegamedb
    username: postgres
    password: dontgotosql
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: user-service