server:
  port: 8082

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    hikari:
      max-lifetime: 600000
    url: jdbc:postgresql://postgres:5432/the_game_user
    username: postgres
    password: dontgotosql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: user-service