server:
  port: 8087

spring:
  application:
    name: conversation-service
  datasource:
    hikari:
      max-lifetime: 600000
    url: jdbc:postgresql://postgres:5432/the_game_conversation
    username: postgres
    password: dontgotosql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: conversation-service



management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    key-values:
      application: conversation-service
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
