server:
  port: 8087

spring:
  application:
    name: conversation-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    hikari:
      max-lifetime: 600000
    url: jdbc:postgresql://postgres:5432/the_game_conversation
    username: postgres
    password: dontgotosql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: conversation-service